declare const styles: {
    teamsAiMeetingApp: string;
    container: string;
    row: string;
    column: string;
    'ms-Grid': string;
    header: string;
    title: string;
    subTitle: string;
    meetingInfo: string;
    content: string;
    section: string;
    statusIndicator: string;
    statusDot: string;
    active: string;
    pulse: string;
    transcriptionPanel: string;
    status: string;
    button: string;
    primary: string;
    summaryPanel: string;
    summaryContent: string;
    loading: string;
    spinner: string;
    spin: string;
    summaryFormatted: string;
    summarySection: string;
    actionItems: string;
    actionItem: string;
    assignee: string;
    dueDate: string;
    welcomePanel: string;
    featureList: string;
    stepsList: string;
    meetingPanel: string;
};
export default styles;
